<script setup>
// @ts-check
import { computed } from 'vue'
import { ref, onMounted, watch } from 'vue'
import * as Tonal from "@tonaljs/tonal";
import { globals } from "../../src/lib/globals.js"
import { sanitiseNoteToSharp, createChordSymbol } from "../../src/lib/note-tools.js"
import { setActiveScaleFilterToMatchChord, setActiveScaleFilter } from "../../src/lib/change-scale.js"
import { noteOptions } from "../../src/lib/note-tools";
import { currentChordInfo } from "../../src/lib/currentChordInfo";
import { chordPlay, auditionInfo } from "../../src/lib/auditionNotes"
import { chordPickerToJammed, chordPickerToJammedExtraPrecision } from "../../src/lib/chordPicker";
import { setChordPicker, setChordSmart, setChordFromSymbol } from "../../src/lib/chordPicker";
import { chordInvert, nextChord, circleOfFifthTranspose, transpose } from "../../src/lib/chordPicker";
import { chordOptions } from "../../src/lib/chordPicker";
import ChordAdd from './ChordAdd.vue'
import CircleOfFifths from './CircleOfFifths.vue';
import CommonChords from './CommonChords.vue';
import ButtonAudition from './ButtonAudition.vue'


// ┌─┐┬ ┬┌─┐┬─┐┌┬┐  ┬─┐┌─┐┌─┐┌┬┐ ┌─┐┌─┐┌┬┐┌┐ ┌─┐
// │  ├─┤│ │├┬┘ ││  ├┬┘│ ││ │ │  │  │ ││││├┴┐│ │
// └─┘┴ ┴└─┘┴└──┴┘  ┴└─└─┘└─┘ ┴  └─┘└─┘┴ ┴└─┘└─┘

const selectedNote = computed({
  get: () => globals.chordPicker.currentRoot,
  set: (v) => {
    globals.chordPicker.currentRoot = v;
    globals.chordPicker.currentBass = sanitiseNoteToSharp(globals.chordPicker.currentRoot)
    chordPickerToJammed()
    chordPlay()
    setActiveScaleFilterToMatchChord(globals.chordPicker.currentRoot, globals.chordPicker.currentChord)
  }
})

// ┌─┐┬ ┬┌─┐┬─┐┌┬┐  ┌┬┐┬ ┬┌─┐┌─┐  ┌─┐┌─┐┌┬┐┌┐ ┌─┐
// │  ├─┤│ │├┬┘ ││   │ └┬┘├─┘├┤   │  │ ││││├┴┐│ │
// └─┘┴ ┴└─┘┴└──┴┘   ┴  ┴ ┴  └─┘  └─┘└─┘┴ ┴└─┘└─┘
// tip: by converting into a computed, need to access the value with chordOptions.value
const selectedChord = computed({
  get: () => globals.chordPicker.currentChord,
  set: (v) => {
    globals.chordPicker.currentChord = v
    globals.chordPicker.currentBass = sanitiseNoteToSharp(globals.chordPicker.currentRoot)
    chordPickerToJammed()
    chordPlay()
    setActiveScaleFilterToMatchChord(globals.chordPicker.currentRoot, globals.chordPicker.currentChord)
  }
})

// ┌─┐┬ ┬┌─┐┬─┐┌┬┐  ┌┐ ┌─┐┌─┐┌─┐  ┌─┐┌─┐┌┬┐┌┐ ┌─┐
// │  ├─┤│ │├┬┘ ││  ├┴┐├─┤└─┐└─┐  │  │ ││││├┴┐│ │
// └─┘┴ ┴└─┘┴└──┴┘  └─┘┴ ┴└─┘└─┘  └─┘└─┘┴ ┴└─┘└─┘
const bassOptions = [{ text: '', value: '' }].concat(noteOptions)
const selectedBass = computed({
  get: () => globals.chordPicker.currentBass,
  set: (v) => {
    globals.chordPicker.currentBass = v;
    chordPickerToJammed()
    chordPlay()
    setActiveScaleFilterToMatchChord(globals.chordPicker.currentRoot, globals.chordPicker.currentChord)
  }
})

function chordFromEvent(eventDetail) {
  const { chordSymbolNoRoot, rootNote, bassNote, state } = eventDetail
  if (state)
    setChordSmart(chordSymbolNoRoot, rootNote, bassNote);
  else {
    chordPlay(false)
    // no need to setActiveScaleFilterToMatchChord() cos its an off state ?
  }
  chordPickerToJammed()
}

function setChordToMatchLhTriggered() {
  // Sync the chord picker combo to the current global lh chord. Does not set
  // the scale - because we don't set the globals.scaleFiltering object here - though we could...
  const { chordSymbolNoRoot, bass, rootNote, chordNotes } = currentChordInfo()
  const success = setChordPicker(chordSymbolNoRoot, bass, rootNote)

  chordPickerToJammed()
  chordPickerToJammedExtraPrecision(chordNotes, bass)

  if (success)
    chordPlay()
}


// ╦  ┬┌─┐┌┬┐┌─┐┌┐┌┌─┐┬─┐┌─┐
// ║  │└─┐ │ ├┤ │││├┤ ├┬┘└─┐
// ╩═╝┴└─┘ ┴ └─┘┘└┘└─┘┴└─└─┘ 

document.addEventListener("syncChordPickerToJamChord", async function (event) {
  // @ts-ignore: event.detail
  let currentChordBeingJammed = event.detail.chordInfo // same as globals.currentChordBeingJammed
  const success = setChordPicker(
    currentChordBeingJammed.type,
    currentChordBeingJammed.bass,
    currentChordBeingJammed.tonic)
  if (success && globals.debugJamChord)
    chordPlay()
  // setActiveScaleFilterToMatchChord()  not sure about this?
})

// for Add, Play etc events generated by shortcut keys in JammerView.vue

document.addEventListener('chord-play', (e) => {
  // @ts-ignore: detail
  const noteState = e.detail.state == 'on'
  chordPlay(noteState)  // get params from globals area later
  setActiveScaleFilterToMatchChord(globals.chordPicker.currentRoot, globals.chordPicker.currentChord)
})
document.addEventListener('chord-invert', (e) => {
  // @ts-ignore: detail
  chordInvert(e.detail.direction)
})
document.addEventListener('chord-fifths', (e) => {
  // @ts-ignore: detail
  circleOfFifthTranspose(e.detail.direction)
})
document.addEventListener('chord-transpose', (e) => {
  // @ts-ignore: detail
  transpose(e.detail.direction)
})

// chordPickerToJammed()  // populated jammed notes from initial state of chordPicker on bootup

function bypassOn() {
  console.log('bypassOn()')
  globals.bypass = true
}

</script>

<template>
  <div class="ui one column grid">

    <!-- main chord column -->
    <div class="column">


      <div class="row">


        <div class="centered row bigbottom">
          👋 Set the Chord Picker below by playing a chord on your Midi Keyboard (<b>toggle 
          <a href="#" @click="bypassOn()"
            :disabled="globals.currentConfigEmpty()">Bypass</a> on</b>
          whilst doing this) OR
          Choose a chord directly from the Chord Picker OR
          Choose a chord from Common Chords
          <span class="mr-2" v-if="!globals.currentConfigEmpty()"> OR click on</span>
          <a href="#" @click.prevent="setChordToMatchLhTriggered()"
            :disabled="globals.currentConfigEmpty()">{{ globals.currentChordName() }}</a> to set the Chord Picker to the
          current {{ globals.currentChordName() }} Project Chord (this is the way to change an exising Project chord).
        </div>

        <!-- chord combo box -->

        <label class="switch-project-padding mr-1">Chord Picker:</label>

        <select v-model="selectedNote">
          <option v-for="option in noteOptions" v-bind:value="option.value" :key="option.value">
            {{ option.text }}
          </option>
        </select>

        <!-- https://fomantic-ui.com/modules/dropdown.html#search-selection -->
        <!-- <select v-model="selectedChord" class="ui search dropdown chordpicker"> -->
        <select v-model="selectedChord">
          <option v-for="option in chordOptions" v-bind:value="option.value" :key="option.value">
            {{ option.text }}
          </option>
        </select>

        /

        <select v-model="selectedBass">
          <option v-for="option in bassOptions" v-bind:value="option.value" :key="option.value">
            {{ option.text }}
          </option>
        </select>

        <span v-if="globals.chordPicker.currentChordInversion != 0" class="ml-1">(inv {{
            globals.chordPicker.currentChordInversion
        }})</span>

        <ButtonAudition title="Audition Chord (keyboard shortcut: F1)" class="ml-3!"
          :notes="auditionInfo().defaultVoicing.notes" :bass="auditionInfo().defaultVoicing.bass" />

      </div>


      <ChordAdd :chord-picker-chord-name="globals.chordPicker.currentRoot + globals.chordPicker.currentChord"
        :chord-tonic="globals.chordPicker.currentRoot" :chord-type="globals.chordPicker.currentChord"
        :chord-inversion="globals.chordPicker.currentChordInversion" :chord-bass="globals.chordPicker.currentBass"
        :audition-info="auditionInfo()" @chord-picker-to-jammed="chordPickerToJammed()" />


      <!-- Accordion with Common Chords -->
      <div class="ui fluid styled accordion" style="background-color: burlywood;">

        <div class="title">
          <i class="dropdown icon"></i>
          Common Chords
        </div>
        <div id="commonChords" class="content">
          <!-- main tab area -->
          <div class="row mt-4">

            <!-- tab header -->
            <div class="ui top attached tabular menu" style="background-color: burlywood;">
              <a class="item active" data-tab="second">Common Chords</a>
              <a class="item" data-tab="third">Circle of Fifths</a>
            </div>

            <!-- Common Chords tab -->
            <div class="ui bottom attached tab segment active" data-tab="second" style="background-color: burlywood;">
              <CommonChords @chord-from-event="chordFromEvent($event.subevent)" />
            </div>

            <!-- Circle of Fifths tab -->
            <div class="ui bottom attached tab segment " data-tab="third" style="background-color: burlywood;">
              <CircleOfFifths @chord-from-event="chordFromEvent($event.subevent)" />
            </div>

          </div> <!-- end tabs -->
        </div> <!-- content -->

        <div class="title">
          <i class="dropdown icon"></i>
          Transpose
        </div>
        <div class="content">
          <div class="row mt-4">

            <div class="centered row bigbottom">

              <button @click="nextChord('prev')" class="ui button tiny">Previous</button>
              <button @click="nextChord('next')" class="ui button tiny">Next</button>
              <button @click="nextChord('random')" class="ui button tiny">Random 🎲</button>

              <button @click="transpose(-1)" class="ui button mini compact" title="Transpose one semitone down">1 <i
                  class="caret down icon"></i></button>
              <button @click="transpose(1)" class="ui button mini compact" title="Transpose one semitone up">1 <i
                  class="caret up icon"></i></button>
              <button @click="circleOfFifthTranspose(-1)" class="ui button mini compact"
                title="Transpose five semitones down (circle of fifths)">5th <i class="caret down icon"></i></button>
              <button @click="circleOfFifthTranspose(1)" class="ui button mini compact"
                title="Transpose five semitones up (circle of fifths)">5th <i class="caret up icon"></i></button>
            </div>

            <div class="centered row">
              <button @click="chordInvert(-1)" class="ui button tiny"
                title="Invert chord voicing down. Open the Active Chord area to see notes.">Inversion <i
                  class="caret left icon"></i></button>
              <button @click="chordInvert(1)" class="ui button tiny"
                title="Invert chord voicing up. Open the Active Chord area to see notes.">Inversion <i
                  class="caret right icon"></i></button>
              <button @click="chordInvert(0)" class="ui button mini compact" title="Reset chord voicing">Reset
                Inversion</button>
            </div>

          </div>
        </div> <!-- content -->

      </div> <!-- end sub accordion - Common Chords -->




      <!-- Accordion with Chord Options -->
      <div class="ui fluid styled accordion" style="background-color: burlywood;">

        <div class="title">
          <i class="dropdown icon"></i>
          Options
        </div>
        <div class="content">
          <div class="row">
            <label class="checkboxLabel" title="Show All possible Chords">
              Show all Chords
              <input type="checkbox" v-model="globals.chordPicker.showAllChords" />
            </label>
            &nbsp;&nbsp;&nbsp;
            <label class="checkboxLabel" title="shortChordNames">
              Short Chord Names
              <input type="checkbox" v-model="globals.chordPicker.shortChordNames" />
            </label>
          </div>

          <div class="row">
            <label class="checkboxLabel" title="Play a chord in Jam area and chord detection will display the chord.">
              Debug Jam Chords
              <input type="checkbox" v-model="globals.debugJamChord" />
            </label>
            &nbsp;&nbsp;&nbsp;
            <label class="checkboxLabel"
              title="Play a chord in Jam area and chord picker will sync to any detected chords.">
              Sync to Jam Chords
              <input type="checkbox" v-model="globals.syncChordPickerToJamChord" />
            </label>

            <label class="checkboxLabel" title="Alter the bass note to match the root note of the inversion.">
              Inversion changes Bass
              <input type="checkbox" v-model="globals.chordPicker.inversionChangesBass" />
            </label>

          </div>
        </div> <!-- content -->
      </div> <!-- accordion options -->


    </div> <!-- main chord column -->


  </div>


</template>

<style scoped>
.chords-that-fit-label {
  font-size: small;
}

.row.bigbottom {
  margin-bottom: 1.5em;
}

.row.bigtop {
  margin-top: 1.5em;
}

.ui.tabular.menu .active.item {
  background: #e0e1e2;
}
</style>
